package com.ecommerce.aims.notification.models;

public enum NotificationEventType {
    RAW_EMAIL,
    ORDER_PAYMENT_SUCCESS,
    ORDER_CONFIRMATION_REQUESTED,
    PASSWORD_RESET,
    ADMIN_PASSWORD_RESET,
    USER_CREATED_BY_ADMIN,
    USER_UPDATED_BY_ADMIN,
    USER_DELETED_BY_ADMIN,
    USER_LOCKED_BY_ADMIN,
    USER_UNLOCKED_BY_ADMIN,
    SUBSCRIPTION_THANK_YOU
}
